source 'http://ruby.taobao.org'

gem 'rails', '4.0.2'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'unicorn'
gem 'execjs'
gem 'therubyracer'
gem 'haml'
gem 'devise', '3.0.3'
gem 'kaminari'

gem 'activemerchant'
gem 'activemerchant_patch_for_china'
gem 'ruby-hmac'